import { K2D } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import type { Metadata } from "next";
import ClientLayout from "@/components/ClientLayout";

const k2d = K2D({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Code with Ameer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={k2d.className}>
          <ClientLayout>{children}</ClientLayout>{" "}
        </body>
      </html>
    </SessionProvider>
  );
}
